from importlib.metadata import PackageNotFoundError, version

from xdrl.compatibility import (
    PRIVATE_UPSTREAM_APIS,
    SUPPORT_DEFINITIONS,
    SUPPORTED_DEPENDENCIES,
    SUPPORTED_GIT_REVISIONS,
    SUPPORTED_PYTHON,
    CompatibilityBoundaryError,
    ConformanceCheck,
    ConformanceSuite,
    GitRevisionRequirement,
    PrivateAPIUsage,
    SupportLevel,
    VersionRequirement,
    WORKFLOW_CONFORMANCE,
    installed_dependency_revisions,
    installed_dependency_versions,
    validate_runtime_compatibility,
)
from xdrl.interactions import (
    AgentSelector,
    InteractionContract,
    InteractionPhase,
    InteractionTopology,
    LifecycleEvent,
    LifecycleEventType,
    MultiAgentSemantics,
    RecurrentCollectorMode,
    RecurrentSemantics,
    RecurrentStateTransition,
    RuntimeInteractionContext,
    SemanticTarget,
)
from xdrl.interventions import (
    Intervention,
    InterventionController,
    InterventionRecord,
    InterventionScope,
    InterventionTarget,
    InterventionTiming,
    InterventionValidationError,
    PairedInterventionResult,
    run_paired,
)
from xdrl.observations import (
    DimensionReduction,
    ObservationKind,
    ObservationRecord,
    ObservationTrace,
    ReductionKind,
    RetentionPolicy,
    TensorRetention,
)
from xdrl.provenance import (
    ArtifactDigestAlgorithm,
    InputArtifactReference,
    InputArtifactRole,
    OutputArtifactReference,
    OutputArtifactRole,
    WORKFLOW_PROVENANCE_SCHEMA_REVISION,
    ProvenanceSchemaError,
    WorkflowCompatibilityEvidence,
    WorkflowExecutionEvidence,
    WorkflowPlanEvidence,
    WorkflowProvenance,
)
from xdrl.tdhook import TDHookWorkflowResult, TDHookWorkflowRunner
from xdrl.types import (
    BatchSemantics,
    ContractModule,
    KeyPresence,
    KeyRole,
    KeySchema,
    ModelRole,
    SchemaValidationError,
    TensorDictKey,
    TensorDictSchema,
    TorchRLModule,
    validate_module,
)

try:
    __version__ = version("xdrl")
except PackageNotFoundError:
    __version__ = "unknown version"

__all__ = [
    "AgentSelector",
    "ArtifactDigestAlgorithm",
    "BatchSemantics",
    "CompatibilityBoundaryError",
    "ConformanceCheck",
    "ConformanceSuite",
    "ContractModule",
    "GitRevisionRequirement",
    "InteractionContract",
    "InteractionPhase",
    "InteractionTopology",
    "Intervention",
    "InterventionController",
    "InterventionRecord",
    "InterventionScope",
    "InterventionTarget",
    "InterventionTiming",
    "InterventionValidationError",
    "InputArtifactReference",
    "InputArtifactRole",
    "KeyPresence",
    "KeyRole",
    "KeySchema",
    "LifecycleEvent",
    "LifecycleEventType",
    "MultiAgentSemantics",
    "ModelRole",
    "ObservationKind",
    "ObservationRecord",
    "ObservationTrace",
    "OutputArtifactReference",
    "OutputArtifactRole",
    "PRIVATE_UPSTREAM_APIS",
    "PrivateAPIUsage",
    "ProvenanceSchemaError",
    "DimensionReduction",
    "ReductionKind",
    "RecurrentCollectorMode",
    "RecurrentSemantics",
    "RecurrentStateTransition",
    "RetentionPolicy",
    "RuntimeInteractionContext",
    "SchemaValidationError",
    "SemanticTarget",
    "SUPPORTED_DEPENDENCIES",
    "SUPPORTED_GIT_REVISIONS",
    "SUPPORTED_PYTHON",
    "SUPPORT_DEFINITIONS",
    "SupportLevel",
    "PairedInterventionResult",
    "TDHookWorkflowResult",
    "TDHookWorkflowRunner",
    "TensorDictSchema",
    "TensorDictKey",
    "TensorRetention",
    "TorchRLModule",
    "VersionRequirement",
    "WORKFLOW_PROVENANCE_SCHEMA_REVISION",
    "WorkflowCompatibilityEvidence",
    "WorkflowExecutionEvidence",
    "WorkflowPlanEvidence",
    "WorkflowProvenance",
    "WORKFLOW_CONFORMANCE",
    "installed_dependency_revisions",
    "installed_dependency_versions",
    "run_paired",
    "validate_module",
    "validate_runtime_compatibility",
]
