seed: 0

env:
  id: mo-mountaincarcontinuous-v0
  continuous_actions: true
  num_envs: 8
  device: cpu

collector:
  frames_per_batch: 2048
  total_frames: 200000
  no_cuda_sync: false

model:
  hidden_dim: 256
  depth: 2

scalarization:
  method: weighted_sum
  in_key: [next, reward]
  out_key: [next, reward]
  preserve_input_key: [next, reward_vector]
  weights: null

loss:
  gamma: 0.99
  lmbda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.0

optim:
  lr: 0.0003
  clip_grad_norm: true
  max_grad_norm: 1.0

train:
  device: cpu
  storing_device: cpu
  frame_skip: 1
  num_epochs: 10
  optim_steps_per_batch: 8
  progress_bar: true
  save_trainer_interval: 10000
  log_interval: 10000

logger:
  backend: wandb
  log_dir: logs
  experiment_name: mogymnasium_ppo
  wandb_kwargs:
    project: xdrl
