algo: qmix
seed: 0

env:
  scenario: balance
  continuous_actions: false
  num_envs: 60
  max_steps: 100
  device: cpu
  scenario_kwargs: {}

collector:
  frames_per_batch: 6000
  total_frames: 10000000
  no_cuda_sync: false

model:
  group: agents
  hidden_dim: 256
  depth: 2
  share_policy_params: true
  mixing_embed_dim: 32

buffer:
  memory_size: 1000000
  init_random_frames: 0

loss:
  gamma: 0.9
  loss_function: l2
  delay_value: true
  soft_target_update: true
  tau: 0.005
  hard_target_update_interval: 5

exploration:
  eps_init: 0.8
  eps_end: 0.01
  anneal_frames: 1000000

optim:
  lr: 0.00005
  clip_grad_norm: true
  max_grad_norm: 5.0

train:
  device: cpu
  storing_device: cpu
  frame_skip: 1
  minibatch_size: 128
  optim_steps_per_batch: 1000

eval:
  enabled: true
  pre_eval: true
  interval_frames: 120000
  episodes: 200
  max_steps: 100
  deterministic: true
  non_deterministic: true
  render: true
  video_fps: 20

logger:
  backend: wandb
  log_dir: logs
  experiment_name: vmas_qmix
  log_hparams: true
  metric_group: agents
  log_interval: 60000
  wandb_kwargs:
    project: xdrl
